# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"
    branches:
      - "*"
      - "!dependabot/**"

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.decide-run.outputs.run }}
    steps:
      - id: decide-run
        shell: bash
        run: |
          if [[ "${{ github.head_ref }}" == *"dependabot"* ]]; then
              echo "Skipping tests for dependabot PRs"
              echo "run=false" >> $GITHUB_OUTPUT
          else
              echo "run=true" >> $GITHUB_OUTPUT  
          fi

  # Ensure project builds before running testing matrix
  build:
    name: Build
    needs: setup
    if: ${{ needs.setup.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: latest

  generate:
    needs: setup
    if: ${{ needs.setup.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      # Temporarily download Terraform 1.8 prerelease for function documentation support.
      # When Terraform 1.8.0 final is released, this can be removed.
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: "1.8.0-alpha20240216"
          terraform_wrapper: false
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Terraform CLI versions
  test:
    name: Terraform Provider Acceptance Tests
    needs: [setup, build]
    if: ${{ needs.setup.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - "1.0.*"
          - "1.1.*"
          - "1.2.*"
          - "1.3.*"
          - "1.4.*"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: ./.github/workflows/setup-mongod.bash
      - run: go mod download
      - env:
          REGISTRY_HOST: registry.terraform.io
          NAMESPACE: 01Joseph-Hwang10
          PROVIDER_NAME: terraform-provider-mongodb
        run: |
          EXEC_ROOT="$(pwd)" \
            TF_ACC=1 \
            TF_ACC_PROVIDER_NAMESPACE="$NAMESPACE" \
            go test ./... \
            -v \
            -parallel 1
        timeout-minutes: 10
